spring.application.name=VaultPay
server.port=${PORT:8080}


spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://ep-young-wind-aiyh9obi-pooler.c-4.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require}
spring.datasource.username=${DB_USER:neondb_owner}
spring.datasource.password=${DB_PASSWORD:npg_H1dhYTU9KkwF}
spring.datasource.driver-class-name=org.postgresql.Driver


spring.jpa.hibernate.ddl-auto=${DDL_AUTO:update}
spring.jpa.show-sql=${SHOW_SQL:true}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=always


spring.docker.compose.skip.embedded=true
spring.docker.compose.enabled=false


logging.level.org.springframework.boot.docker.compose=DEBUG
logging.level.org.springframework.boot.autoconfigure.docker=DEBUG
