spring.application.name=VaultPay


spring.datasource.url=${DATABASE_URL:jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:vault}?sslmode=require}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:123}
spring.datasource.driver-class-name=org.postgresql.Driver


spring.jpa.hibernate.ddl-auto=${DDL_AUTO:update}
spring.jpa.show-sql=${SHOW_SQL:true}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=always


spring.docker.compose.skip.embedded=true
spring.docker.compose.enabled=false


logging.level.org.springframework.boot.docker.compose=DEBUG
logging.level.org.springframework.boot.autoconfigure.docker=DEBUG
